// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRecentFile(arg1:string):Promise<void>;

export function ClearCurrentFile():Promise<main.CurrentFilesState>;

export function CreateDir(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetContentHash(arg1:string):Promise<string>;

export function GetCurrentFilesState():Promise<main.CurrentFilesState>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetFileContentPreview(arg1:string):Promise<string>;

export function GetRecentFiles():Promise<Array<string>>;

export function GetShowHiddenFiles():Promise<boolean>;

export function GoUp():Promise<main.CurrentFilesState>;

export function Greet(arg1:string):Promise<string>;

export function ListFiles(arg1:string):Promise<Array<main.FileEntry>>;

export function OpenFile(arg1:string):Promise<main.CurrentFilesState>;

export function PickImageFile():Promise<string>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function ResolveImagePath(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SetShowHiddenFiles(arg1:boolean):Promise<void>;

export function SetWindowTitle(arg1:string):Promise<void>;

export function UpdateConfig(arg1:string):Promise<void>;

export function UpdateConfigField(arg1:string,arg2:string):Promise<void>;

export function UpdateWindowTitleWithCurrentDir():Promise<void>;
