// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFile(arg1) {
  return window['go']['main']['App']['AddRecentFile'](arg1);
}

export function ClearCurrentFile() {
  return window['go']['main']['App']['ClearCurrentFile']();
}

export function CreateDir(arg1) {
  return window['go']['main']['App']['CreateDir'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContentHash(arg1) {
  return window['go']['main']['App']['GetContentHash'](arg1);
}

export function GetCurrentFilesState() {
  return window['go']['main']['App']['GetCurrentFilesState']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetFileContentPreview(arg1) {
  return window['go']['main']['App']['GetFileContentPreview'](arg1);
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetShowHiddenFiles() {
  return window['go']['main']['App']['GetShowHiddenFiles']();
}

export function GoUp() {
  return window['go']['main']['App']['GoUp']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PickImageFile() {
  return window['go']['main']['App']['PickImageFile']();
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function ResolveImagePath(arg1) {
  return window['go']['main']['App']['ResolveImagePath'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SetShowHiddenFiles(arg1) {
  return window['go']['main']['App']['SetShowHiddenFiles'](arg1);
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateConfigField(arg1, arg2) {
  return window['go']['main']['App']['UpdateConfigField'](arg1, arg2);
}

export function UpdateWindowTitleWithCurrentDir() {
  return window['go']['main']['App']['UpdateWindowTitleWithCurrentDir']();
}
